[package]
name = "construccion-compilador"
version = "0.1.0"
authors = ["Fran Guijarro <franleplant@gmail.com>"]

build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.15.2"
regex = "0.2.0"


[build-dependencies]
lalrpop = "0.15.2"
